[env:attiny85_sensor]
platform  = atmelavr@4.2.0
board     = attiny85

board_build.f_cpu = 8000000L

upload_protocol = custom
upload_flags =
    -C$PACKAGES_DIR/tool-avrdude/avrdude.conf
    -v
    -pattiny85
    -cusbasp
    -Pusb
    -U lfuse:w:0xE2:m
    -U hfuse:w:0xDF:m
    -U efuse:w:0xFF:m

upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i

build_flags =
    -DARDUINO_attiny85
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -fno-strict-aliasing
    -fno-exceptions

; ZERO bibliotecas de terceiros — tudo implementado em drivers raw
; lib_deps removido intencionalmente