[env:esp32_gateway_atuador]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    jgromes/RadioLib
    knolleary/PubSubClient
    RobTillaart/PCF8574
    https://github.com/johnrickman/LiquidCrystal_I2C.git
